---
- name: Build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']

- name: Copy etcd.conf file
  copy: src=etcd.conf dest=/etc/etcd/etcd.conf
    
- name: Copy kubernetes/apiserver
  copy: src=apiserver dest=/etc/kubernetes/apiserver

- name: Start etcd service
  systemd: name=etcd state=started

- name: Create overlay network
  command: etcdctl mkdir /kube/network
  
- name: Copy flannel config file
  copy: src=flannel-config.json dest=/tmp/flannel-config.json

- name: Configure overlay network
  shell: etcdctl set /kube/network/config < /tmp/flannel-config.json

- name: Restart services
  systemd: name={{ item }} state=restarted enabled=True
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - flanneld
